application_port: 8000
# Not defining DB settings here, we always have DATABASE_URL available
# database:
#   host: "127.0.0.1"
#   port: 5432
#   username: "postgres"
#   password: "password"
#   database_name: "newsletter"
