name: Test
on:
  push:
  pull_request:
    types: [reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
        with:
          # Only this step sets the cache for future runs
          cache-to: type=gha,mode=max
      - name: fmt
        run: docker-compose run --no-deps web fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Clippy
        run: >
          docker-compose run web /bin/sh -c '
          sqlx migrate run &&
          cargo clippy
          '

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup-docker-compose
      - name: Test
        run: >
          docker-compose run web /bin/sh -c '
          sqlx migrate run &&
          cargo test
          '
